[package]
name = "Shadow-RPG"
version = "0.1.0"
authors = ["Joshua Astray <JoshuaSRKF@gmail.com>"]

[dependencies]
num-rational = "0.1.37"
piston = "0.32.0"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.37.0"
piston2d-opengl_graphics = "0.43.1"
